/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserNameRouteImport } from './routes/user.$name'
import { Route as ProjectSlugRouteImport } from './routes/project.$slug'
import { Route as OrganizationNameRouteImport } from './routes/organization.$name'
import { Route as DiscoverCategoryRouteImport } from './routes/discover.$category'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserNameRoute = UserNameRouteImport.update({
  id: '/user/$name',
  path: '/user/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugRoute = ProjectSlugRouteImport.update({
  id: '/project/$slug',
  path: '/project/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationNameRoute = OrganizationNameRouteImport.update({
  id: '/organization/$name',
  path: '/organization/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverCategoryRoute = DiscoverCategoryRouteImport.update({
  id: '/discover/$category',
  path: '/discover/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover/$category': typeof DiscoverCategoryRoute
  '/organization/$name': typeof OrganizationNameRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/user/$name': typeof UserNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover/$category': typeof DiscoverCategoryRoute
  '/organization/$name': typeof OrganizationNameRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/user/$name': typeof UserNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discover/$category': typeof DiscoverCategoryRoute
  '/organization/$name': typeof OrganizationNameRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/user/$name': typeof UserNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover/$category'
    | '/organization/$name'
    | '/project/$slug'
    | '/user/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover/$category'
    | '/organization/$name'
    | '/project/$slug'
    | '/user/$name'
  id:
    | '__root__'
    | '/'
    | '/discover/$category'
    | '/organization/$name'
    | '/project/$slug'
    | '/user/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverCategoryRoute: typeof DiscoverCategoryRoute
  OrganizationNameRoute: typeof OrganizationNameRoute
  ProjectSlugRoute: typeof ProjectSlugRoute
  UserNameRoute: typeof UserNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$name': {
      id: '/user/$name'
      path: '/user/$name'
      fullPath: '/user/$name'
      preLoaderRoute: typeof UserNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$slug': {
      id: '/project/$slug'
      path: '/project/$slug'
      fullPath: '/project/$slug'
      preLoaderRoute: typeof ProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/$name': {
      id: '/organization/$name'
      path: '/organization/$name'
      fullPath: '/organization/$name'
      preLoaderRoute: typeof OrganizationNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/$category': {
      id: '/discover/$category'
      path: '/discover/$category'
      fullPath: '/discover/$category'
      preLoaderRoute: typeof DiscoverCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverCategoryRoute: DiscoverCategoryRoute,
  OrganizationNameRoute: OrganizationNameRoute,
  ProjectSlugRoute: ProjectSlugRoute,
  UserNameRoute: UserNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
